version: "3"
services:
    postgres:
      container_name: postgres_service
      image: postgres:12
      volumes:
        - ./backend/data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=ott_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432

    django:
      container_name: django_service
      build:
        context: ./backend
        dockerfile: ./backend/Dockerfile
      working_dir: /home/
      command: >
        bash -c "
        chmod +x /wait-for-it.sh
        && /wait-for-it.sh postgres:5432 -t 10 # 5432 포트 사용 가능 시까지 대기
        && python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver"
      volumes:
        - ./:/home/
      depends_on:
        - postgres
      ports:
        - "8000:8000"
