version: "3"
services:
    postgres:
      container_name: postgres_service
      image: postgres:12
      volumes:
        - ./backend/data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=ott_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432

    django:
      container_name: django_service
      working_dir: /home/ubuntu/Together/backend
      command: "python manage.py runserver"
      build: ./backend
      volumes:
        - .:/home/ubuntu/Together/backend
      depends_on:
        - postgres
      ports:
        - "8000:8000"
