version: "3"
services:
    web:
      build: ./backend
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - .:/code
      depends_on:
        - db
    
    db:
      image: postgres:12
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=ott_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root

    web_front:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - ./