version: "3"
services:
    web:
      build: ./backend
      command: python manage.py runserver 8000:8000
      ports:
        - "8000:8000"
      volumes:
        - .:/backend
      depends_on:
        - db
    
    db:
      image: postgres:12
      volumes:
        - ./backend/data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=ott_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root

