version: '3'
services:
    web:
      build: .
      commnad: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - .:/web
      depends_on:
        - db
    
    db:
      image: postgres:13.4
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
